#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/granite_docling_hybrid/modular_granite_docling_hybrid.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_granite_docling_hybrid.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig, PretrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring, logging
from ..auto import CONFIG_MAPPING


logger = logging.get_logger(__name__)


@auto_docstring(checkpoint="HuggingFaceM4/GraniteDoclingHybrid-8B-Llama3")
@strict
class GraniteDoclingHybridVisionConfig(PreTrainedConfig):
    r"""
    Example:

    ```python
    >>> from transformers.models.granite_docling_hybrid.modeling_granite_docling_hybrid import GraniteDoclingHybridVisionTransformer
    >>> from transformers.models.granite_docling_hybrid.configuration_granite_docling_hybrid import GraniteDoclingHybridVisionConfig

    >>> # Initializing a GraniteDoclingHybridVisionConfig with google/siglip-base-patch16-224 style configuration
    >>> configuration = GraniteDoclingHybridVisionConfig()

    >>> # Initializing a GraniteDoclingHybridVisionTransformer (with random weights) from the google/siglip-base-patch16-224 style configuration
    >>> model = GraniteDoclingHybridVisionTransformer(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "granite_docling_hybrid_vision"
    base_config_key = "vision_config"

    hidden_size: int = 1152
    intermediate_size: int = 3072
    num_hidden_layers: int = 12
    num_attention_heads: int = 16
    num_channels: int = 3
    image_size: int | list[int] | tuple[int, int] = 224
    patch_size: int | list[int] | tuple[int, int] = 32
    hidden_act: str = "gelu_pytorch_tanh"
    layer_norm_eps: float = 1e-6
    attention_dropout: float | int = 0.0
    initializer_range: float = 0.02


@auto_docstring(checkpoint="ibm-granite/granite-speech-3.2-8b")
@strict
class GraniteDoclingHybridTextConfig(PreTrainedConfig):
    r"""
    embedding_multiplier (`float`, *optional*, defaults to 1.0):
        embedding multiplier.
    logits_scaling (`float`, *optional*, defaults to 1.0):
        divisor for output logits.
    residual_multiplier (`float`, *optional*, defaults to 1.0):
        residual multiplier.
    attention_multiplier (`float`, *optional*, defaults to 1.0):
        attention multiplier.
    shared_intermediate_size (`int`, *optional*, defaults to 1024):
        intermediate size for shared experts.
    position_embedding_type (`str`, *optional*):
        Positional embedding type to be used; defaults to None. Allowed options: `[None, "rope"]`

    Example:

    ```python
    >>> from transformers import GraniteDoclingHybridTextModel, GraniteDoclingHybridTextConfig

    >>> # Initializing a GraniteDoclingHybridText config
    >>> configuration = GraniteDoclingHybridTextConfig()

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "granite_docling_hybrid_text"
    attribute_map = {
        "layers_block_type": "layer_types",
    }
    keys_to_ignore_at_inference = ["past_key_values"]

    vocab_size: int = 32000
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = None
    hidden_act: str = "silu"
    max_position_embeddings: int = 2048
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    tie_word_embeddings: bool = False
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    attention_dropout: float | int | None = 0.0
    embedding_multiplier: int | float | None = 1.0
    logits_scaling: int | float | None = 1.0
    residual_multiplier: int | float | None = 1.0
    attention_multiplier: int | float | None = 1.0
    num_local_experts: int | None = 8
    num_experts_per_tok: int | None = 2
    output_router_logits: bool | None = False
    router_aux_loss_coef: float | None = 0.001
    shared_intermediate_size: int = 1024
    position_embedding_type: str | None = None
    layer_types: list[str] | None = None
    mamba_n_heads: int | None = 128
    mamba_n_groups: int | None = 1
    mamba_d_state: int | None = 256
    mamba_d_head: int | str | None = "auto"
    mamba_d_conv: int | None = 4
    mamba_expand: int | None = 2
    mamba_chunk_size: int | None = 256
    mamba_conv_bias: bool | None = True
    mamba_proj_bias: bool | None = False
    time_step_min: float | None = 0.001
    time_step_max: float | None = 0.1
    time_step_limit: list[float, float] | tuple[float, float] | None = (0.0, float("inf"))

    def __post_init__(self, **kwargs):
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        mamba_intermediate = self.mamba_expand * self.hidden_size
        if self.mamba_d_head == "auto":
            self.mamba_d_head = mamba_intermediate // self.mamba_n_heads

        self.time_step_limit = tuple(self.time_step_limit) if self.time_step_limit is not None else None
        if self.layer_types is None:
            self.layer_types = ["mamba"] * self.num_hidden_layers

        super().__post_init__(**kwargs)

    def validate_architecture(self):
        """Part of `@strict`-powered validation. Validates the architecture of the config."""

        mamba_intermediate = self.mamba_expand * self.hidden_size
        if mamba_intermediate % self.mamba_n_heads != 0:
            raise ValueError("mamba_n_heads must divide mamba_expand * hidden_size")

        if self.mamba_d_head * self.mamba_n_heads != mamba_intermediate:
            raise ValueError("The dimensions for the Mamba head state do not match the model intermediate_size")

    # overwrite the function to use in `HybridMambaAttentionDynamicCache`
    @property
    def layers_block_type(self):
        return self.layer_types


class GraniteDoclingHybridConfig(PretrainedConfig):
    r"""
    This is the configuration class to store the configuration of a [`GraniteDoclingHybridModel`]. It is used to instantiate a
    GraniteDoclingHybrid model according to the specified arguments, defining the model architecture. Instantiating a
    configuration with the defaults will yield a similar configuration to that of the Idefics3 model architecture,
    but with a GraniteMoeHybrid text model.

    Configuration objects inherit from [`PretrainedConfig`] and can be used to control the model outputs. Read the
    documentation from [`PretrainedConfig`] for more information.

    Args:
        image_token_id (`int`, *optional*, defaults to 128257):
            The id of the "image" token.
        tie_word_embeddings (`bool`, *optional*, defaults to `False`):
            Whether or not to tie the word embeddings with the token embeddings.
        vision_config (`GraniteDoclingHybridVisionConfig` or `dict`, *optional*, defaults to `GraniteDoclingHybridVisionConfig`):
            Custom vision config or dict for the vision tower
        text_config (`PretrainedConfig` or `dict`, *optional*, defaults to `GraniteMoeHybridConfig`):
            Custom text config or dict for the text model
        scale_factor (`int`, *optional*, defaults to 2):
            The scale factor for the image encoder.
        mp_pooling_mode (`str`, *optional*, defaults to `"pixel_shuffle"`):
            Modality-projector variant. Supported: `"pixel_shuffle"`, `"pixel_shuffle_mlp"`,
            `"pixel_shuffle_mlp_v2"`. The two MLP variants add a post-projection GELU + Linear
            channel mix in LM space; `v2` additionally inserts pre-shuffle / mid / post LayerNorms
            and a within-tile 2D sincos positional embedding (matching MiniCPM-style resamplers).
            The structure mirrors nanoVLM's `mp_pooling_mode`.
        use_deepstack (`bool`, *optional*, defaults to `False`):
            Whether to enable Qwen3-VL-style DeepStack: intermediate ViT block outputs are projected
            through dedicated mergers and added (residually) to the LM hidden states at image-token
            positions after specific decoder layers. See https://arxiv.org/abs/2406.04334.
        deepstack_visual_indexes (`list[int]`, *optional*, defaults to `[3, 6, 9]`):
            Indices of vision encoder blocks whose outputs (pre-final-LayerNorm) feed DeepStack.
            Slot `i` of this list is paired with slot `i` of `deepstack_attn_layers`.
        deepstack_attn_layers (`list[int]`, *optional*, defaults to `[10, 13, 17]`):
            Indices of language model decoder layers that receive the residual visual injection
            from the corresponding ViT tap. Same length as `deepstack_visual_indexes`.

    Example:
    ```python
    >>> from transformers import GraniteDoclingHybridModel, GraniteDoclingHybridConfig
    >>> # Initializing configuration
    >>> configuration = GraniteDoclingHybridConfig()
    >>> # Initializing a model from the configuration
    >>> model = GraniteDoclingHybridModel(configuration)
    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "granite_docling_hybrid"
    sub_configs = {"text_config": CONFIG_MAPPING, "vision_config": GraniteDoclingHybridVisionConfig}

    def __init__(
        self,
        image_token_id=128257,
        tie_word_embeddings=False,
        vision_config=None,
        text_config=None,
        scale_factor=2,
        mp_pooling_mode="pixel_shuffle",
        use_deepstack=False,
        deepstack_visual_indexes=None,
        deepstack_attn_layers=None,
        **kwargs,
    ):
        self.image_token_id = image_token_id
        self.tie_word_embeddings = tie_word_embeddings

        if vision_config is None:
            self.vision_config = GraniteDoclingHybridVisionConfig()
            logger.info("vision_config is None, using default vision config")
        elif isinstance(vision_config, dict):
            self.vision_config = GraniteDoclingHybridVisionConfig(**vision_config)
        elif isinstance(vision_config, GraniteDoclingHybridVisionConfig):
            self.vision_config = vision_config

        if isinstance(text_config, dict):
            text_config["model_type"] = text_config.get("model_type", "granitemoehybrid")
            text_config = CONFIG_MAPPING[text_config["model_type"]](**text_config)
        elif text_config is None:
            logger.info("text_config is None, using default GraniteMoeHybrid text config")
            text_config = CONFIG_MAPPING["granitemoehybrid"]()

        self.text_config = text_config
        self.scale_factor = scale_factor

        if mp_pooling_mode not in ("pixel_shuffle", "pixel_shuffle_mlp", "pixel_shuffle_mlp_v2"):
            raise ValueError(
                f"Unknown mp_pooling_mode={mp_pooling_mode!r}. Supported: "
                "'pixel_shuffle', 'pixel_shuffle_mlp', 'pixel_shuffle_mlp_v2'."
            )
        self.mp_pooling_mode = mp_pooling_mode

        self.use_deepstack = use_deepstack
        self.deepstack_visual_indexes = (
            list(deepstack_visual_indexes) if deepstack_visual_indexes is not None else [3, 6, 9]
        )
        self.deepstack_attn_layers = list(deepstack_attn_layers) if deepstack_attn_layers is not None else [10, 13, 17]
        if len(self.deepstack_visual_indexes) != len(self.deepstack_attn_layers):
            raise ValueError(
                "deepstack_visual_indexes and deepstack_attn_layers must have the same length "
                f"(got {len(self.deepstack_visual_indexes)} vs {len(self.deepstack_attn_layers)})."
            )

        super().__init__(**kwargs, tie_word_embeddings=tie_word_embeddings)


__all__ = ["GraniteDoclingHybridConfig"]
