#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/granite_docling_hybrid/modular_granite_docling_hybrid.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_granite_docling_hybrid.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import re
from functools import lru_cache
from typing import TYPE_CHECKING, Union

import numpy as np
import torch

from ...feature_extraction_utils import BatchFeature
from ...image_utils import ImageInput, is_valid_image, load_image
from ...processing_utils import MultiModalData, ProcessingKwargs, ProcessorMixin, Unpack
from ...tokenization_utils_base import AddedToken, BatchEncoding, TextInput
from ...utils import auto_docstring


if TYPE_CHECKING:
    from ...tokenization_utils_base import PreTokenizedInput


## Processing ##


class GraniteDoclingHybridProcessorKwargs(ProcessingKwargs, total=False):
    _defaults = {
        "text_kwargs": {
            "add_special_tokens": True,
            "padding": False,
            "is_split_into_words": False,
            "return_mm_token_type_ids": False,
        },
    }


def is_url(val) -> bool:
    return isinstance(val, str) and val.startswith("http")


@lru_cache(maxsize=100)
def get_optimal_tiled_canvas(
    original_image_size: tuple[int, int],
    target_tile_size: tuple[int, int],
    min_image_tiles: int,
    max_image_tiles: int,
) -> tuple[int, int]:
    """
    Given a minimum and maximum number of tiles, find the canvas with the closest aspect ratio to the
    original image aspect ratio.
    In case of tie-breaking condition when two canvases have the same aspect ratio difference, we favor the canvas with
    more tiles, until the area covered by the tiles is more than twice the target area, in order to avoid unnecessarily
    excessive tiling.
    """
    possible_tile_arrangements = get_all_supported_aspect_ratios(min_image_tiles, max_image_tiles)

    original_height, original_width = original_image_size
    target_tile_height, target_tile_width = target_tile_size
    aspect_ratio = original_width / original_height
    area = original_width * original_height

    # find the grid with the best aspect ratio
    best_ratio_diff = float("inf")
    best_grid = (1, 1)
    for grid in possible_tile_arrangements:
        grid_aspect_ratio = grid[0] / grid[1]
        ratio_diff = abs(aspect_ratio - grid_aspect_ratio)
        if ratio_diff < best_ratio_diff:
            best_ratio_diff = ratio_diff
            best_grid = grid
        elif ratio_diff == best_ratio_diff:
            # if the aspect ratio difference is the same, we favor the grid with more patches
            # until the area covered by the patches is more than twice the original image area
            if area > 0.5 * target_tile_height * target_tile_width * grid[0] * grid[1]:
                best_grid = grid

    return best_grid


@lru_cache(maxsize=10)
def get_all_supported_aspect_ratios(min_image_tiles: int, max_image_tiles: int) -> list[tuple[int, int]]:
    """
    Computes all allowed aspect ratios for a given minimum and maximum number of input tiles.

    This function calculates all possible arrangements of tiles that can be formed
    within the constraint of the minimum and maximum number of tiles. Each arrangement is
    represented by its aspect ratio (width/height) and the corresponding tile configuration.

    Args:
        min_image_tiles (`int`):
            The minimum number of tiles allowed.
        max_image_tiles (`int`):
            The maximum number of tiles allowed.

    Returns:
        `list[tuple[int, int]]`: A list of tuples, each tuple representing a valid (width, height)
        configuration in terms of number of tiles.

    Example:
        >>> get_all_supported_aspect_ratios(1, 4)
        [(1, 1), (1, 2), (2, 1), (1, 3), (3, 1), (1, 4), (2, 2), (4, 1)]

    """
    aspect_ratios = []
    for width in range(1, max_image_tiles + 1):
        for height in range(1, max_image_tiles + 1):
            if width * height <= max_image_tiles and width * height >= min_image_tiles:
                aspect_ratios.append((width, height))

    aspect_ratios = sorted(aspect_ratios, key=lambda x: x[0] * x[1])

    return aspect_ratios


def _prompt_split_image(image_seq_len, image_rows, image_cols, fake_token_around_image, image_token, global_img_token):
    """Prompt with expanded image tokens for when the image is split into patches.

    Only includes the global thumbnail token when there are multiple tiles (image_rows * image_cols > 1),
    matching the nanoVLM training-time behavior. GotOcr2ImageProcessor likewise only appends the
    thumbnail patch when the image is split into more than one tile.
    """
    text_split_images = ""
    for n_h in range(image_rows):
        for n_w in range(image_cols):
            text_split_images += (
                f"{fake_token_around_image}" + f"<row_{n_h + 1}_col_{n_w + 1}>" + f"{image_token}" * image_seq_len
            )
        text_split_images += "\n"

    if image_rows * image_cols > 1:
        text_split_images += (
            f"\n{fake_token_around_image}"
            + f"{global_img_token}"
            + f"{image_token}" * image_seq_len
            + f"{fake_token_around_image}"
        )
    return text_split_images


def _prompt_single_image(image_seq_len, fake_token_around_image, image_token, global_img_token):
    """Prompt with expanded image tokens for a single image (no tiles)."""
    return (
        f"{fake_token_around_image}"
        + f"{global_img_token}"
        + f"{image_token}" * image_seq_len
        + f"{fake_token_around_image}"
    )


def get_image_prompt_string(
    image_rows, image_cols, image_seq_len, fake_token_around_image, image_token, global_img_token
):
    if image_rows == 0 and image_cols == 0:
        return _prompt_single_image(
            image_seq_len,
            fake_token_around_image=fake_token_around_image,
            image_token=image_token,
            global_img_token=global_img_token,
        )
    return _prompt_split_image(
        image_seq_len, image_rows, image_cols, fake_token_around_image, image_token, global_img_token
    )


def _compact_prompt_split_image(image_rows, image_cols, fake_token_around_image, global_img_token):
    """Compact version of _prompt_split_image without repeated <image> tokens.

    Image tokens are inserted post-tokenization via _expand_image_tokens_in_ids,
    avoiding the cost of tokenizing hundreds of identical <image> placeholder strings
    (recipe ⑦ from Huang et al., 2026 — a primary TTFT bottleneck for compact VLMs).
    """
    text = ""
    for n_h in range(image_rows):
        for n_w in range(image_cols):
            text += f"{fake_token_around_image}<row_{n_h + 1}_col_{n_w + 1}>"
        text += "\n"
    if image_rows * image_cols > 1:
        text += f"\n{fake_token_around_image}{global_img_token}{fake_token_around_image}"
    return text


def _compact_prompt_single_image(fake_token_around_image, global_img_token):
    """Compact version of _prompt_single_image without repeated <image> tokens."""
    return f"{fake_token_around_image}{global_img_token}{fake_token_around_image}"


def get_compact_image_prompt_string(image_rows, image_cols, fake_token_around_image, global_img_token):
    """Returns a compact prompt string without repeated <image> tokens.

    Used for efficient tokenization: the tokenizer only processes structural tokens
    (fake/row_col/global), and image tokens are spliced into input_ids afterwards.
    """
    if image_rows == 0 and image_cols == 0:
        return _compact_prompt_single_image(fake_token_around_image, global_img_token)
    return _compact_prompt_split_image(image_rows, image_cols, fake_token_around_image, global_img_token)


@auto_docstring
class GraniteDoclingHybridProcessor(ProcessorMixin):
    def __init__(self, image_processor, tokenizer=None, image_seq_len: int = 169, chat_template=None, **kwargs):
        r"""
        image_seq_len (`int`, *optional*, defaults to 169):
            The length of the image sequence i.e. the number of <image> tokens per image in the input.
            This parameter is used to build the string from the input prompt and image tokens and should match the
            value the model used. It is computed as: image_seq_len = int(((image_size // patch_size) ** 2) / (scale_factor**2))
        """
        self.fake_image_token = AddedToken("<fake_token_around_image>", normalized=False, special=True).content
        self.image_token = AddedToken("<image>", normalized=False, special=True).content
        self.end_of_utterance_token = AddedToken("<end_of_utterance>", normalized=False, special=True).content
        self.global_image_tag = "<global-img>"  # https://github.com/huggingface/transformers/pull/32473/files/8063e5e17362571b693f1db95167f5443a3be1b2#r1734825341
        self.image_seq_len = image_seq_len
        self.image_token_id = tokenizer.convert_tokens_to_ids(self.image_token)
        self.fake_image_token_id = tokenizer.convert_tokens_to_ids(self.fake_image_token)
        self.global_image_token_id = tokenizer.convert_tokens_to_ids(self.global_image_tag)
        # Cover up to 16×16 grids (max_patches=256); stored as a set for O(1) lookup
        # during post-tokenization image-token expansion. Filters out the tokenizer's UNK id
        # so unknown row/col tokens don't collapse to a single entry. `unk_token_id` is
        # inlined into the comprehension because the modular converter drops bare local
        # variables when it merges the parent class's __init__ body.
        self.row_col_ids = self._collect_row_col_ids(tokenizer)

        # This regex matches one or more occurrences of <global-img> tags (optionally surrounded by newline characters)
        # or <row_x_col_y> tags (where x and y are digits, also optionally surrounded by newline characters).
        self._regex_to_remove_extra_special_tokens = re.compile(r"(\n?<global-img>\n?|<row_\d+_col_\d+>\n?)+")

        tokens_to_add = {
            "additional_special_tokens": [
                self.fake_image_token,
                self.image_token,
                self.end_of_utterance_token,
            ]
        }
        tokenizer.add_special_tokens(tokens_to_add)
        self.image_token_id = tokenizer.convert_tokens_to_ids(self.image_token)

        super().__init__(image_processor, tokenizer, chat_template=chat_template, **kwargs)

    def _extract_images_from_prompts(self, prompts):
        prompt_images = []
        for prompt in prompts:
            images = []
            for elem in prompt:
                if is_valid_image(elem):
                    images.append(elem)
                elif is_url(elem):
                    images.append(load_image(elem))
            prompt_images.append(images)
        return prompt_images

    @auto_docstring
    def __call__(
        self,
        images: ImageInput | list[ImageInput] | list[list[ImageInput]] = None,
        text: Union[TextInput, "PreTokenizedInput", list[TextInput], list["PreTokenizedInput"]] = None,
        audio=None,
        videos=None,
        **kwargs: Unpack[GraniteDoclingHybridProcessorKwargs],
    ) -> BatchEncoding:
        """
        Processes the input prompts and returns a BatchEncoding.

        This method extends the Idefics3Processor to handle GotOcr2ImageProcessor specifics.

        Args:
            images (`PIL.Image.Image`, `np.ndarray`, `torch.Tensor`, `list[PIL.Image.Image]`, `list[np.ndarray]`, `list[torch.Tensor]`, *optional*):
                The image or batch of images to be prepared. Each image can be a PIL image, NumPy array or PyTorch
                tensor. If is of type `list[ImageInput]`, it's assumed that this is for a single prompt i.e. of batch size 1.
            text (`Union[TextInput, PreTokenizedInput, list[TextInput], list[PreTokenizedInput]]`, *optional*):
                The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
                (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set
                `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
                Wherever an image token, `<image>` is encountered it is expanded to
                `<fake_token_around_image>` + `<row_x_col_y>` + `<image>` * `image_seq_len` * <fake_token_around_image>`.
            return_tensors (`Union[str, TensorType]`, *optional*):
                If set, will return tensors of a particular framework. See [`PreTrainedTokenizerFast.__call__`] for more
                information.
        """
        if text is None and images is None:
            raise ValueError("You must provide either `text` or `images`.")

        output_kwargs = self._merge_kwargs(
            GraniteDoclingHybridProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )

        return_mm_token_type_ids = output_kwargs["text_kwargs"].pop("return_mm_token_type_ids", False)
        return_tensors = output_kwargs["text_kwargs"].pop("return_tensors", None)

        n_images_in_text = []
        n_images_in_images = []
        inputs = {}

        if text is not None:
            if isinstance(text, str):
                text = [text]
            elif not isinstance(text, list) and not isinstance(text[0], str):
                raise ValueError("Invalid input text. Please provide a string, or a list of strings")
            n_images_in_text = [sample.count(self.image_token) for sample in text]

        if images is not None:
            images = self.image_processor.fetch_images(images)
            n_images_in_images = [len(sample) if isinstance(sample, (list, tuple)) else 1 for sample in images]
            images = [[sample] if not isinstance(sample, (list, tuple)) else sample for sample in images]

            # Recipe ⑧ (Huang et al. 2026 §3.3): skip CPU-side rescale + normalize so
            # pixel_values are transferred as uint8 (1 byte/pixel) instead of float32
            # (4 bytes) or bfloat16 (2 bytes). The model normalizes on GPU instead.
            uint8_kwargs = dict(output_kwargs["images_kwargs"])
            uint8_kwargs["do_rescale"] = False
            uint8_kwargs["do_normalize"] = False
            image_inputs = self.image_processor(images, **uint8_kwargs)
            # Convert float32 [0, 255] → uint8 [0, 255]: lossless for integer-valued pixels
            pv = image_inputs.get("pixel_values")
            if pv is not None:
                image_inputs["pixel_values"] = pv.to(dtype=torch.uint8)
            inputs.update(image_inputs)

            if text is not None:
                if n_images_in_images != n_images_in_text:
                    raise ValueError(
                        f"The number of images in the text {n_images_in_text} and images {n_images_in_images} should be the same."
                    )

                # GotOcr2ImageProcessor doesn't return rows/cols, compute them
                image_rows = []
                image_cols = []
                for sample_images in images:
                    sample_image_rows = []
                    sample_image_cols = []
                    for img in sample_images:
                        width, height = img.size
                        n_cols, n_rows = get_optimal_tiled_canvas(
                            (height, width),
                            (
                                self.image_processor.size["height"],
                                self.image_processor.size["width"],
                            ),
                            self.image_processor.min_patches,
                            self.image_processor.max_patches,
                        )
                        sample_image_rows.append(n_rows)
                        sample_image_cols.append(n_cols)
                    image_rows.append(sample_image_rows)
                    image_cols.append(sample_image_cols)

                # Post-process inputs for GotOcr2ImageProcessor
                num_patches_arr = inputs.pop("num_patches", None)
                pixel_values = inputs.get("pixel_values")
                if pixel_values is not None and len(pixel_values.shape) == 4:
                    # TODO: change
                    # Make 5D to match Idefics3 expected format: (batch, num_images, C, H, W)
                    # pixel_values is (total_sub_images, C, H, W) — a flat concat of all patches
                    # from all images. We need to group them per sample and pad to the max
                    # patch count so the tensor is rectangular.  The Idefics3 model's
                    # get_image_features will filter out zero-padded (all-zero) sub-images.
                    batch_size = len(images)

                    # Compute number of sub-images per sample (sum patches of each image in the sample)
                    if num_patches_arr is not None:
                        img_offset = 0
                        patches_per_sample = []
                        for sample_imgs in images:
                            n_imgs = len(sample_imgs)
                            patches_per_sample.append(int(sum(num_patches_arr[img_offset : img_offset + n_imgs])))
                            img_offset += n_imgs
                    else:
                        # Fallback: assume equal distribution
                        total = pixel_values.shape[0]
                        patches_per_sample = [total // batch_size] * batch_size

                    max_patches = max(patches_per_sample)
                    if all(p == max_patches for p in patches_per_sample):
                        # All samples have the same number of sub-images — simple reshape
                        inputs["pixel_values"] = pixel_values.reshape(batch_size, max_patches, *pixel_values.shape[1:])
                    else:
                        # Variable sub-image counts — pad shorter samples with zeros
                        # (the model filters out all-zero sub-images in get_image_features)
                        padded = torch.zeros(
                            batch_size,
                            max_patches,
                            *pixel_values.shape[1:],
                            dtype=pixel_values.dtype,
                            device=pixel_values.device,
                        )
                        pv_offset = 0
                        for i, count in enumerate(patches_per_sample):
                            padded[i, :count] = pixel_values[pv_offset : pv_offset + count]
                            pv_offset += count
                        inputs["pixel_values"] = padded

                    # TODO: change
                    # Explicit mask so get_image_features can distinguish real
                    # sub-images from zero-padding without relying on pixel values
                    # (a genuinely all-black tile would otherwise be dropped).
                    pam = torch.zeros(batch_size, max_patches, dtype=torch.bool)
                    for i, count in enumerate(patches_per_sample):
                        pam[i, :count] = True
                    inputs["pixel_attention_mask"] = pam

                fake_image_token = self.fake_image_token
                image_token = self.image_token
                global_img_token = self.global_image_tag

                prompt_strings = []  # full expanded — only used for _check_special_mm_tokens
                compact_prompt_strings = []  # compact — used for tokenization (no repeated <image> tokens)
                batch_image_seq_lengths = []
                for sample, sample_rows, sample_cols in zip(text, image_rows, image_cols):
                    image_prompt_strings = []
                    compact_image_prompt_strings = []
                    image_seq_lengths = []
                    for n_rows, n_cols in zip(sample_rows, sample_cols):
                        image_prompt_string = get_image_prompt_string(
                            n_rows,
                            n_cols,
                            self.image_seq_len,
                            image_token=image_token,
                            fake_token_around_image=fake_image_token,
                            global_img_token=global_img_token,
                        )
                        compact_image_prompt_string = get_compact_image_prompt_string(
                            n_rows,
                            n_cols,
                            fake_token_around_image=fake_image_token,
                            global_img_token=global_img_token,
                        )
                        # Add +2 and +3 for special BOI/EOI/fake_image_wrapper tokens
                        row_length = (self.image_seq_len + 2) * n_cols + 1
                        image_seq_lengths.append((self.image_seq_len + 3) + row_length * n_rows)
                        image_prompt_strings.append(image_prompt_string)
                        compact_image_prompt_strings.append(compact_image_prompt_string)

                    batch_image_seq_lengths.append(image_seq_lengths)
                    split_sample = sample.split(image_token)
                    if len(split_sample) == 0:
                        raise ValueError("The image token should be present in the text.")

                    full_sample = split_sample[0]
                    compact_sample = split_sample[0]
                    for i, (full_str, compact_str) in enumerate(
                        zip(image_prompt_strings, compact_image_prompt_strings)
                    ):
                        full_sample += full_str + split_sample[i + 1]
                        compact_sample += compact_str + split_sample[i + 1]
                    prompt_strings.append(full_sample)
                    compact_prompt_strings.append(compact_sample)

                # Tokenize compact prompts — avoids tokenizing N*image_seq_len repeated
                # '<image>' strings (recipe ⑦, Huang et al. 2026 §3.3).
                text_inputs = self.tokenizer(compact_prompt_strings, **output_kwargs["text_kwargs"])

                # Expand: splice image_seq_len <image> token IDs after each row/col and
                # global-img marker. Result is identical to full-prompt tokenization.
                input_ids = text_inputs["input_ids"]
                attention_mask = text_inputs.get("attention_mask", [[1] * len(ids) for ids in input_ids])
                expanded_ids, expanded_mask = self._expand_image_tokens_in_ids(input_ids, attention_mask)
                # TODO: change
                # Pad expanded sequences to uniform length so they can be stacked
                # into a tensor. Different images produce different tile counts,
                # so post-expansion lengths vary across the batch.
                max_len = max(len(ids) for ids in expanded_ids)
                pad_id = self.tokenizer.pad_token_id
                expanded_ids = [ids + [pad_id] * (max_len - len(ids)) for ids in expanded_ids]
                expanded_mask = [m + [0] * (max_len - len(m)) for m in expanded_mask]

                text_inputs["input_ids"] = expanded_ids
                if "attention_mask" in text_inputs:
                    text_inputs["attention_mask"] = expanded_mask

                self._check_special_mm_tokens(prompt_strings, text_inputs, modalities=["image"])
                inputs.update(text_inputs)

        elif text is not None:
            if any(n_images_in_text):
                raise ValueError(
                    f"Found {sum(n_images_in_text)} {self.image_token} tokens in the text but no images were passed."
                )
            text_inputs = self.tokenizer(text=text, **output_kwargs["text_kwargs"])
            inputs.update(text_inputs)

        if return_mm_token_type_ids:
            array_ids = np.array(inputs["input_ids"])
            mm_token_type_ids = np.zeros_like(array_ids)
            for i, seq_lengths in enumerate(batch_image_seq_lengths):
                image_start_positions = np.where(array_ids[i] == self.fake_image_token_id)[0]
                j = 0
                for seq_len in seq_lengths:
                    if j >= len(image_start_positions):
                        break
                    start = image_start_positions[j]
                    end = start + seq_len
                    mm_token_type_ids[i, start:end] = 1
                    j = np.searchsorted(image_start_positions, end)

            inputs["mm_token_type_ids"] = mm_token_type_ids.tolist()

        return BatchFeature(data=inputs, tensor_type=return_tensors)

    def create_mm_token_type_ids(self, input_ids: list, batch_image_seq_lengths: list[int]) -> list[list[int]]:
        # We have to iterate for each list separately because inputs
        # might be non-padded lists and we can't cast numpy on that!
        # Then cast numpy as each input for faster indexing
        mm_token_type_ids = []
        for i, seq_lengths in enumerate(batch_image_seq_lengths):
            array_ids = np.array(input_ids[i])
            mm_token_types = np.zeros_like(array_ids)
            image_start_positions = np.where(array_ids == self.fake_image_token_id)[0]
            j = 0
            for seq_len in seq_lengths:
                if j >= len(image_start_positions):
                    break
                start = image_start_positions[j]
                end = start + seq_len
                mm_token_types[start:end] = 1
                j = np.searchsorted(image_start_positions, end)
            mm_token_type_ids.append(mm_token_types.tolist())

        return mm_token_type_ids

    def _get_num_multimodal_tokens(self, image_sizes=None, **kwargs):
        """
        Computes the number of placeholder tokens needed for multimodal inputs with the given sizes.

        Args:
            image_sizes (`list[list[int]]`, *optional*):
                The input sizes formatted as (height, width) per each image.

        Returns:
            `MultiModalData`: A `MultiModalData` object holding number of tokens per each of the provided
            input modalities, along with other useful data.
        """

        vision_data = {}
        if image_sizes is not None:
            images_kwargs = GraniteDoclingHybridProcessorKwargs._defaults.get("images_kwargs", {})
            images_kwargs.update(kwargs)

            num_image_row_cols = [
                self.image_processor.get_number_of_image_patches(*image_size, images_kwargs)
                for image_size in image_sizes
            ]

            base_image_length = self.image_seq_len + 3
            col_length = self.image_seq_len + 2
            num_image_tokens = []
            num_image_patches = []

            for num_patches, num_rows, num_cols in num_image_row_cols:
                row_length = col_length * num_cols + 1
                num_image_tokens.append(base_image_length + (row_length * num_rows))
                num_image_patches.append(num_patches)

            vision_data.update({"num_image_tokens": num_image_tokens, "num_image_patches": num_image_patches})

        return MultiModalData(**vision_data)

    @staticmethod
    def _collect_row_col_ids(tokenizer) -> set[int]:
        if tokenizer is None:
            return set()
        unk_id = tokenizer.unk_token_id
        return {
            tid
            for tid in (
                tokenizer.convert_tokens_to_ids(f"<row_{i + 1}_col_{j + 1}>") for i in range(16) for j in range(16)
            )
            if tid != unk_id
        }

    def _expand_image_tokens_in_ids(
        self,
        input_ids: list[list[int]],
        attention_mask: list[list[int]],
    ) -> tuple[list[list[int]], list[list[int]]]:
        """Insert image_seq_len <image> token IDs after each row/col and global-img marker.

        This is the counterpart to compact tokenization (recipe ⑦, Huang et al. 2026):
        instead of tokenizing a prompt that contains hundreds of repeated '<image>' strings,
        we tokenize a compact version and expand here with a fast Python list splice.

        The resulting input_ids are identical to what full-prompt tokenization produces,
        so the model forward pass is unaffected.
        """
        image_token_id = self.image_token_id
        row_col_ids = self.row_col_ids  # set[int]
        global_id = self.global_image_token_id
        image_seq_len = self.image_seq_len
        image_fill = [image_token_id] * image_seq_len
        mask_fill = [1] * image_seq_len

        expanded_ids = []
        expanded_mask = []
        for ids_row, mask_row in zip(input_ids, attention_mask):
            new_ids: list[int] = []
            new_mask: list[int] = []
            for tok_id, m in zip(ids_row, mask_row):
                new_ids.append(tok_id)
                new_mask.append(m)
                if tok_id in row_col_ids or tok_id == global_id:
                    new_ids.extend(image_fill)
                    new_mask.extend(mask_fill)
            expanded_ids.append(new_ids)
            expanded_mask.append(new_mask)
        return expanded_ids, expanded_mask
