#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/granite_for_docling/modular_granite_for_docling.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_granite_for_docling.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Adapted from transformers.models.idefics3, granitemoehybrid, and nanoVLM connector patterns
from typing import TYPE_CHECKING

from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig, PretrainedConfig
from ...utils import auto_docstring, logging
from ..auto import CONFIG_MAPPING


if TYPE_CHECKING:
    from ...modeling_rope_utils import RopeParameters


logger = logging.get_logger(__name__)


@auto_docstring(checkpoint="HuggingFaceM4/GraniteForDocling-8B-Llama3")
@strict
class GraniteForDoclingVisionConfig(PreTrainedConfig):
    r"""
    Example:

    ```python
    >>> from transformers.models.granite_for_docling.modeling_granite_for_docling import GraniteForDoclingVisionTransformer
    >>> from transformers.models.granite_for_docling.configuration_granite_for_docling import GraniteForDoclingVisionConfig

    >>> # Initializing a GraniteForDoclingVisionConfig with google/siglip-base-patch16-224 style configuration
    >>> configuration = GraniteForDoclingVisionConfig()

    >>> # Initializing a GraniteForDoclingVisionTransformer (with random weights) from the google/siglip-base-patch16-224 style configuration
    >>> model = GraniteForDoclingVisionTransformer(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "granite_for_docling_vision"
    base_config_key = "vision_config"

    hidden_size: int = 1152
    intermediate_size: int = 3072
    num_hidden_layers: int = 12
    num_attention_heads: int = 16
    num_channels: int = 3
    image_size: int | list[int] | tuple[int, int] = 224
    patch_size: int | list[int] | tuple[int, int] = 32
    hidden_act: str = "gelu_pytorch_tanh"
    layer_norm_eps: float = 1e-6
    attention_dropout: float | int = 0.0
    initializer_range: float = 0.02


@auto_docstring
class GraniteForDoclingTextConfig(PretrainedConfig):
    r"""
    Configuration for the dense Granite-style text decoder used in [`GraniteForDoclingModel`].
    """

    model_type = "granite_for_docling_text"
    base_config_key = "text_config"
    keys_to_ignore_at_inference = ["past_key_values"]

    vocab_size: int = 32000
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = None
    hidden_act: str = "silu"
    max_position_embeddings: int = 2048
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    tie_word_embeddings: bool = False
    rope_parameters: "RopeParameters | dict | None" = None
    attention_bias: bool = False
    attention_dropout: float | int | None = 0.0
    embedding_multiplier: float | int | None = 1.0
    logits_scaling: float | int | None = 1.0
    residual_multiplier: float | int | None = 1.0
    attention_multiplier: float | int | None = 1.0
    shared_intermediate_size: int = 1024
    position_embedding_type: str = "rope"

    def __post_init__(self, **kwargs):
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads
        super().__post_init__(**kwargs)


class GraniteForDoclingConfig(PretrainedConfig):
    r"""
    Configuration for [`GraniteForDoclingModel`]: a SigLIP vision tower, modality projector,
    and dense Granite-style text decoder with optional DeepStack visual injections.

    Args:
        image_token_id (`int`, *optional*, defaults to 128257):
            The id of the "image" token.
        tie_word_embeddings (`bool`, *optional*, defaults to `False`):
            Whether or not to tie the word embeddings with the token embeddings.
        vision_config (`GraniteForDoclingVisionConfig` or `dict`, *optional*):
            Custom vision config or dict for the vision tower.
        text_config (`GraniteForDoclingTextConfig` or `dict`, *optional*):
            Custom text config or dict for the text model.
        scale_factor (`int`, *optional*, defaults to 4):
            The scale factor for the image encoder projector.
        mp_pooling_mode (`str`, *optional*, defaults to `"pixel_shuffle_mlp_v2"`):
            Modality-projector variant. Supported: `"pixel_shuffle"`, `"pixel_shuffle_mlp_v2"`.
        use_deepstack (`bool`, *optional*, defaults to `True`):
            Whether to inject intermediate ViT features into selected decoder layers at image-token
            positions.
        deepstack_visual_indexes (`list[int]`, *optional*, defaults to `[3, 7, 10]`):
            Vision encoder block indices whose outputs feed DeepStack. Slot `i` pairs with
            `deepstack_attn_layers[i]`.
        deepstack_attn_layers (`list[int]`, *optional*, defaults to `[0, 1, 2]`):
            Text decoder layer indices that receive the corresponding DeepStack visual tap.
    """

    model_type = "granite_for_docling"
    sub_configs = {"text_config": GraniteForDoclingTextConfig, "vision_config": GraniteForDoclingVisionConfig}

    def __init__(
        self,
        image_token_id=128257,
        tie_word_embeddings=False,
        vision_config=None,
        text_config=None,
        scale_factor=4,
        mp_pooling_mode="pixel_shuffle_mlp_v2",
        use_deepstack=True,
        deepstack_visual_indexes=None,
        deepstack_attn_layers=None,
        **kwargs,
    ):
        self.image_token_id = image_token_id
        self.tie_word_embeddings = tie_word_embeddings

        if vision_config is None:
            self.vision_config = GraniteForDoclingVisionConfig()
            logger.info("vision_config is None, using default vision config")
        elif isinstance(vision_config, dict):
            self.vision_config = GraniteForDoclingVisionConfig(**vision_config)
        elif isinstance(vision_config, GraniteForDoclingVisionConfig):
            self.vision_config = vision_config

        if isinstance(text_config, dict):
            text_config["model_type"] = text_config.get("model_type", "granite_for_docling_text")
            text_config = CONFIG_MAPPING[text_config["model_type"]](**text_config)
        elif text_config is None:
            logger.info("text_config is None, using default GraniteForDocling text config")
            text_config = GraniteForDoclingTextConfig()

        self.text_config = text_config
        self.scale_factor = scale_factor

        if mp_pooling_mode not in ("pixel_shuffle", "pixel_shuffle_mlp_v2"):
            raise ValueError(
                f"Unknown mp_pooling_mode={mp_pooling_mode!r}. Supported: 'pixel_shuffle', 'pixel_shuffle_mlp_v2'."
            )
        self.mp_pooling_mode = mp_pooling_mode

        self.use_deepstack = use_deepstack
        self.deepstack_visual_indexes = (
            list(deepstack_visual_indexes) if deepstack_visual_indexes is not None else [3, 7, 10]
        )
        self.deepstack_attn_layers = list(deepstack_attn_layers) if deepstack_attn_layers is not None else [0, 1, 2]
        if len(self.deepstack_visual_indexes) != len(self.deepstack_attn_layers):
            raise ValueError(
                "deepstack_visual_indexes and deepstack_attn_layers must have the same length "
                f"(got {len(self.deepstack_visual_indexes)} vs {len(self.deepstack_attn_layers)})."
            )

        super().__init__(**kwargs, tie_word_embeddings=tie_word_embeddings)


__all__ = ["GraniteForDoclingConfig", "GraniteForDoclingTextConfig", "GraniteForDoclingVisionConfig"]
