#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/granite_for_docling/modular_granite_for_docling.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_granite_for_docling.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Adapted from transformers.models.idefics3, granitemoehybrid, and nanoVLM connector patterns
from typing import TYPE_CHECKING

from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig, PretrainedConfig
from ...utils import auto_docstring, logging
from ..auto import CONFIG_MAPPING


if TYPE_CHECKING:
    from ...modeling_rope_utils import RopeParameters


logger = logging.get_logger(__name__)


@auto_docstring(checkpoint="HuggingFaceM4/GraniteForDocling-8B-Llama3")
@strict
class GraniteForDoclingVisionConfig(PreTrainedConfig):
    r"""
    Example:

    ```python
    >>> from transformers.models.granite_for_docling.modeling_granite_for_docling import GraniteForDoclingVisionTransformer
    >>> from transformers.models.granite_for_docling.configuration_granite_for_docling import GraniteForDoclingVisionConfig

    >>> # Initializing a GraniteForDoclingVisionConfig with google/siglip-base-patch16-224 style configuration
    >>> configuration = GraniteForDoclingVisionConfig()

    >>> # Initializing a GraniteForDoclingVisionTransformer (with random weights) from the google/siglip-base-patch16-224 style configuration
    >>> model = GraniteForDoclingVisionTransformer(configuration)

    >>> # Accessing the model configuration
    >>> configuration = model.config
    ```"""

    model_type = "granite_for_docling_vision"
    base_config_key = "vision_config"

    hidden_size: int = 1152
    intermediate_size: int = 3072
    num_hidden_layers: int = 12
    num_attention_heads: int = 16
    num_channels: int = 3
    image_size: int | list[int] | tuple[int, int] = 224
    patch_size: int | list[int] | tuple[int, int] = 32
    hidden_act: str = "gelu_pytorch_tanh"
    layer_norm_eps: float = 1e-6
    attention_dropout: float | int = 0.0
    initializer_range: float = 0.02


@auto_docstring
class GraniteForDoclingTextConfig(PretrainedConfig):
    r"""
    Configuration for the dense Granite-style text decoder used in [`GraniteForDoclingModel`].

    shared_intermediate_size (`int`, *optional*, defaults to 1024):
        Intermediate size of the shared MLP (`shared_mlp`) in each decoder layer.
    position_embedding_type (`str`, *optional*, defaults to `"rope"`):
        Positional embedding type. Supported: `"rope"`.
    """

    model_type = "granite_for_docling_text"
    base_config_key = "text_config"
    keys_to_ignore_at_inference = ["past_key_values"]

    vocab_size: int = 32000
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = None
    hidden_act: str = "silu"
    max_position_embeddings: int = 2048
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-6
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    tie_word_embeddings: bool = False
    rope_parameters: "RopeParameters | dict | None" = None
    attention_bias: bool = False
    attention_dropout: float | int | None = 0.0
    embedding_multiplier: float | int | None = 1.0
    logits_scaling: float | int | None = 1.0
    residual_multiplier: float | int | None = 1.0
    attention_multiplier: float | int | None = 1.0
    shared_intermediate_size: int = 1024
    position_embedding_type: str = "rope"

    def __post_init__(self, **kwargs):
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads
        super().__post_init__(**kwargs)


class GraniteForDoclingConfig(PretrainedConfig):
    r"""
    Configuration for [`GraniteForDoclingModel`]: a SigLIP vision tower, modality projector,
    and dense Granite-style text decoder with optional DeepStack visual injections.

    Args:
        image_token_id (`int`, *optional*, defaults to 128257):
            The id of the "image" token.
        tie_word_embeddings (`bool`, *optional*, defaults to `False`):
            Whether or not to tie the word embeddings with the token embeddings.
        vision_config (`GraniteForDoclingVisionConfig` or `dict`, *optional*):
            Custom vision config or dict for the vision tower.
        text_config (`GraniteForDoclingTextConfig` or `dict`, *optional*):
            Custom text config or dict for the text model.
        scale_factor (`int`, *optional*, defaults to 4):
            The scale factor for the image encoder projector.
        mp_pooling_mode (`str`, *optional*, defaults to `"pixel_shuffle_mlp_v2"`):
            Modality-projector variant. Supported: `"pixel_shuffle"`, `"pixel_shuffle_mlp_v2"`.
        mp_adaptive_input_mode (`str`, *optional*, defaults to `"none"`):
            `"token_rate"` adds the dense-page fine projector path: tiles flagged fine are pixel-shuffled
            at `scale_factor / 2` through `connector.proj_fine`, emitting 4x tokens per tile. The prompt
            must reserve the matching placeholder count per tile — the route is decided BEFORE the forward
            (by the processor / caller); the model only follows the per-tile mask it is handed.
        use_deepstack (`bool`, *optional*, defaults to `True`):
            Whether to inject intermediate ViT features into selected decoder layers at image-token
            positions.
        deepstack_visual_indexes (`list[int]`, *optional*, defaults to `[3, 7, 10]`):
            Vision encoder block indices whose outputs feed DeepStack. Slot `i` pairs with
            `deepstack_attn_layers[i]`.
        deepstack_attn_layers (`list[int]`, *optional*, defaults to `[0, 1, 2]`):
            Text decoder layer indices that receive the corresponding DeepStack visual tap.
        use_mtp (`bool`, *optional*, defaults to `False`):
            Attach optional Multi-Token Prediction draft heads for speculative decoding.
            Off by default; existing checkpoints are unchanged.
        mtp_num_heads (`int`, *optional*, defaults to `0`):
            Number of MTP heads (K). Head `i` predicts token t+2+i.
        mtp_weight (`float`, *optional*, defaults to `0.3`):
            Weight of the mean MTP CE relative to the main LM loss when labels are passed.
        mtp_loss_chunk_size (`int`, *optional*, defaults to `1024`):
            Sequence chunk size for per-head CE (bounds the fp32 logits buffer).
        mtp_num_heads_attn (`int`, *optional*):
            Attention heads inside each MTP block. Defaults to the decoder's `num_attention_heads`.
        mtp_ffn_dim (`int`, *optional*):
            FFN width of each MTP block. Defaults to the decoder's `intermediate_size`.
        mtp_dropout (`float`, *optional*, defaults to `0.0`):
            Dropout inside the MTP `TransformerEncoderLayer`.
        mtp_use_speculative (`bool`, *optional*, defaults to `False`):
            When True, `generate(..., use_speculative=True)` (the default if this flag is set)
            runs greedy speculative decoding with the MTP heads.
        mtp_draft_vocab_file (`str`, *optional*):
            Optional frequency-ranked draft vocabulary JSON (relative to the model dir).
            The draft argmax is restricted to those rows; the target still verifies the
            full vocab so decoding stays lossless.
    """

    model_type = "granite_for_docling"
    sub_configs = {"text_config": GraniteForDoclingTextConfig, "vision_config": GraniteForDoclingVisionConfig}

    def __init__(
        self,
        image_token_id=128257,
        tie_word_embeddings=False,
        vision_config=None,
        text_config=None,
        scale_factor=4,
        mp_pooling_mode="pixel_shuffle_mlp_v2",
        mp_adaptive_input_mode="none",
        use_deepstack=True,
        deepstack_visual_indexes=None,
        deepstack_attn_layers=None,
        use_mtp=False,
        mtp_num_heads=0,
        mtp_weight=0.3,
        mtp_loss_chunk_size=1024,
        mtp_num_heads_attn=None,
        mtp_ffn_dim=None,
        mtp_dropout=0.0,
        mtp_use_speculative=False,
        mtp_draft_vocab_file=None,
        **kwargs,
    ):
        self.image_token_id = image_token_id
        self.tie_word_embeddings = tie_word_embeddings

        if vision_config is None:
            self.vision_config = GraniteForDoclingVisionConfig()
            logger.info("vision_config is None, using default vision config")
        elif isinstance(vision_config, dict):
            self.vision_config = GraniteForDoclingVisionConfig(**vision_config)
        elif isinstance(vision_config, GraniteForDoclingVisionConfig):
            self.vision_config = vision_config

        if isinstance(text_config, dict):
            text_config["model_type"] = text_config.get("model_type", "granite_for_docling_text")
            text_config = CONFIG_MAPPING[text_config["model_type"]](**text_config)
        elif text_config is None:
            logger.info("text_config is None, using default GraniteForDocling text config")
            text_config = GraniteForDoclingTextConfig()

        self.text_config = text_config
        self.scale_factor = scale_factor

        if mp_pooling_mode not in ("pixel_shuffle", "pixel_shuffle_mlp_v2"):
            raise ValueError(
                f"Unknown mp_pooling_mode={mp_pooling_mode!r}. Supported: 'pixel_shuffle', 'pixel_shuffle_mlp_v2'."
            )
        self.mp_pooling_mode = mp_pooling_mode

        if mp_adaptive_input_mode not in ("none", "token_rate"):
            raise ValueError(
                f"Unknown mp_adaptive_input_mode={mp_adaptive_input_mode!r}. Supported: 'none', 'token_rate'."
            )
        if mp_adaptive_input_mode == "token_rate":
            if mp_pooling_mode != "pixel_shuffle_mlp_v2":
                raise ValueError("mp_adaptive_input_mode='token_rate' requires mp_pooling_mode='pixel_shuffle_mlp_v2'.")
            if scale_factor % 2:
                raise ValueError("mp_adaptive_input_mode='token_rate' requires an even scale_factor.")
        self.mp_adaptive_input_mode = mp_adaptive_input_mode

        self.use_deepstack = use_deepstack
        self.deepstack_visual_indexes = (
            list(deepstack_visual_indexes) if deepstack_visual_indexes is not None else [3, 7, 10]
        )
        self.deepstack_attn_layers = list(deepstack_attn_layers) if deepstack_attn_layers is not None else [0, 1, 2]
        if len(self.deepstack_visual_indexes) != len(self.deepstack_attn_layers):
            raise ValueError(
                "deepstack_visual_indexes and deepstack_attn_layers must have the same length "
                f"(got {len(self.deepstack_visual_indexes)} vs {len(self.deepstack_attn_layers)})."
            )

        self.use_mtp = bool(use_mtp)
        self.mtp_num_heads = int(mtp_num_heads or 0)
        self.mtp_weight = float(mtp_weight)
        self.mtp_loss_chunk_size = int(mtp_loss_chunk_size or 0)
        self.mtp_num_heads_attn = (
            int(mtp_num_heads_attn) if mtp_num_heads_attn is not None else None
        )
        self.mtp_ffn_dim = int(mtp_ffn_dim) if mtp_ffn_dim is not None else None
        self.mtp_dropout = float(mtp_dropout or 0.0)
        self.mtp_use_speculative = bool(mtp_use_speculative)
        self.mtp_draft_vocab_file = mtp_draft_vocab_file
        if self.use_mtp and self.mtp_num_heads <= 0:
            raise ValueError("use_mtp=True requires mtp_num_heads > 0")

        super().__init__(**kwargs, tie_word_embeddings=tie_word_embeddings)


__all__ = ["GraniteForDoclingConfig", "GraniteForDoclingTextConfig", "GraniteForDoclingVisionConfig"]
