#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/granite_for_docling/modular_granite_for_docling.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_granite_for_docling.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Adapted from transformers.models.idefics3, granitemoehybrid, and nanoVLM connector patterns

import re
from functools import lru_cache
from itertools import accumulate
from typing import TYPE_CHECKING, Union

import numpy as np
import torch

from ...feature_extraction_utils import BatchFeature
from ...image_utils import ImageInput, is_valid_image
from ...processing_utils import MultiModalData, ProcessingKwargs, ProcessorMixin, Unpack
from ...tokenization_utils_base import AddedToken, BatchEncoding, TextInput
from ...utils import auto_docstring


if TYPE_CHECKING:
    from ...tokenization_utils_base import PreTokenizedInput


## Processing ##


class GraniteForDoclingProcessorKwargs(ProcessingKwargs, total=False):
    _defaults = {
        "text_kwargs": {
            "add_special_tokens": True,
            "padding": False,
            "is_split_into_words": False,
            "return_mm_token_type_ids": False,
        },
    }


# The doclang tokenizer's tile-position vocab (<row_r_col_c>) covers r, c in 1..16 only.
# GotOcr2's get_all_supported_aspect_ratios has no per-dimension cap, so an extreme-aspect-ratio
# crop (e.g. a 322x19 equation line, with our max_patches=32) can pick a grid like (1, 24): the
# marker token for a column/row past 16 doesn't exist in the vocab, so _expand_image_tokens_in_ids
# silently drops that tile's image-token block instead of raising, producing an off-by-one-tile
# mismatch between the text and image embeddings. Capped local copies below fix the row/col count
# used for the prompt; _install_tile_grid_dim_cap keeps the shared GotOcr2 image processor's own
# pixel tiling (a separate code path) in agreement with it.
MAX_TILE_GRID_DIM = 16


@lru_cache(maxsize=10)
def get_all_supported_aspect_ratios(min_image_tiles: int, max_image_tiles: int) -> list[tuple[int, int]]:
    """Same as GotOcr2's get_all_supported_aspect_ratios, restricted to grids that fit MAX_TILE_GRID_DIM."""
    max_dim = min(max_image_tiles, MAX_TILE_GRID_DIM)
    aspect_ratios = []
    for width in range(1, max_dim + 1):
        for height in range(1, max_dim + 1):
            if max_image_tiles >= width * height >= min_image_tiles:
                aspect_ratios.append((width, height))
    return sorted(aspect_ratios, key=lambda x: x[0] * x[1])


@lru_cache(maxsize=100)
def get_optimal_tiled_canvas(
    original_image_size: tuple[int, int],
    target_tile_size: tuple[int, int],
    min_image_tiles: int,
    max_image_tiles: int,
) -> tuple[int, int]:
    """Same selection logic as GotOcr2's get_optimal_tiled_canvas, over the capped candidates above."""
    possible_tile_arrangements = get_all_supported_aspect_ratios(min_image_tiles, max_image_tiles)

    original_height, original_width = original_image_size
    target_tile_height, target_tile_width = target_tile_size
    aspect_ratio = original_width / original_height
    area = original_width * original_height

    best_ratio_diff = float("inf")
    best_grid = (1, 1)
    for grid in possible_tile_arrangements:
        grid_aspect_ratio = grid[0] / grid[1]
        ratio_diff = abs(aspect_ratio - grid_aspect_ratio)
        if ratio_diff < best_ratio_diff:
            best_ratio_diff = ratio_diff
            best_grid = grid
        elif ratio_diff == best_ratio_diff:
            if area > 0.5 * target_tile_height * target_tile_width * grid[0] * grid[1]:
                best_grid = grid

    return best_grid


def _install_tile_grid_dim_cap() -> None:
    """Apply the same cap to the shared GotOcr2 image processor's own tiling.

    ``GraniteForDoclingProcessor.image_processor`` is a stock GotOcr2ImageProcessor(Fast)
    instance; its ``crop_image_to_patches`` calls ``get_optimal_tiled_canvas`` /
    ``get_all_supported_aspect_ratios`` from ``got_ocr2.image_processing_got_ocr2`` directly, a
    separate function object from the capped copies above. Without this, the actual pixel tiling
    and the prompt's row/col tokens (computed with the capped versions above) could disagree.
    """
    from ..got_ocr2 import image_processing_got_ocr2 as _got_ocr2_slow

    orig = _got_ocr2_slow.get_all_supported_aspect_ratios
    if getattr(orig, "_tile_grid_dim_capped", False):
        return

    @lru_cache(maxsize=32)
    def _capped(min_image_tiles: int, max_image_tiles: int):
        return [
            grid
            for grid in orig(min_image_tiles, max_image_tiles)
            if grid[0] <= MAX_TILE_GRID_DIM and grid[1] <= MAX_TILE_GRID_DIM
        ]

    _capped._tile_grid_dim_capped = True
    _got_ocr2_slow.get_all_supported_aspect_ratios = _capped
    _got_ocr2_slow.get_optimal_tiled_canvas.cache_clear()


def _prompt_split_image(image_seq_len, image_rows, image_cols, fake_token_around_image, image_token, global_img_token):
    """Prompt with expanded image tokens for when the image is split into patches.

    Only includes the global thumbnail token when there are multiple tiles (image_rows * image_cols > 1),
    matching the training-time behavior. GotOcr2ImageProcessor likewise only appends the
    thumbnail patch when the image is split into more than one tile.
    """
    text_split_images = ""
    for n_h in range(image_rows):
        for n_w in range(image_cols):
            text_split_images += (
                f"{fake_token_around_image}" + f"<row_{n_h + 1}_col_{n_w + 1}>" + f"{image_token}" * image_seq_len
            )
        text_split_images += "\n"

    if image_rows * image_cols > 1:
        text_split_images += (
            f"\n{fake_token_around_image}"
            + f"{global_img_token}"
            + f"{image_token}" * image_seq_len
            + f"{fake_token_around_image}"
        )
    return text_split_images


def _prompt_single_image(image_seq_len, fake_token_around_image, image_token, global_img_token):
    """Prompt with expanded image tokens for a single image (no tiles)."""
    return (
        f"{fake_token_around_image}"
        + f"{global_img_token}"
        + f"{image_token}" * image_seq_len
        + f"{fake_token_around_image}"
    )


def get_image_prompt_string(
    image_rows, image_cols, image_seq_len, fake_token_around_image, image_token, global_img_token
):
    if image_rows == 0 and image_cols == 0:
        return _prompt_single_image(
            image_seq_len,
            fake_token_around_image=fake_token_around_image,
            image_token=image_token,
            global_img_token=global_img_token,
        )
    return _prompt_split_image(
        image_seq_len, image_rows, image_cols, fake_token_around_image, image_token, global_img_token
    )


def _compact_prompt_split_image(image_rows, image_cols, fake_token_around_image, global_img_token):
    """Compact prompt without repeated <image> tokens; expansion happens post-tokenization."""
    text = ""
    for n_h in range(image_rows):
        for n_w in range(image_cols):
            text += f"{fake_token_around_image}<row_{n_h + 1}_col_{n_w + 1}>"
        text += "\n"
    if image_rows * image_cols > 1:
        text += f"\n{fake_token_around_image}{global_img_token}{fake_token_around_image}"
    return text


def _compact_prompt_single_image(fake_token_around_image, global_img_token):
    """Compact prompt for a single image without repeated <image> tokens."""
    return f"{fake_token_around_image}{global_img_token}{fake_token_around_image}"


def get_compact_image_prompt_string(image_rows, image_cols, fake_token_around_image, global_img_token):
    """Returns a compact prompt string without repeated <image> tokens."""
    if image_rows == 0 and image_cols == 0:
        return _compact_prompt_single_image(fake_token_around_image, global_img_token)
    return _compact_prompt_split_image(image_rows, image_cols, fake_token_around_image, global_img_token)


@auto_docstring
class GraniteForDoclingProcessor(ProcessorMixin):
    valid_processor_kwargs = GraniteForDoclingProcessorKwargs

    def __init__(self, image_processor, tokenizer=None, image_seq_len: int = 169, chat_template=None, **kwargs):
        r"""
        image_seq_len (`int`, *optional*, defaults to 169):
            The length of the image sequence i.e. the number of <image> tokens per image in the input.
            This parameter is used to build the string from the input prompt and image tokens and should match the
            value the model used. It is computed as: image_seq_len = int(((image_size // patch_size) ** 2) / (scale_factor**2))
        """
        # Must run before any tiling happens: caps the shared GotOcr2 image processor's
        # own crop grid to match the tokenizer vocab (see MAX_TILE_GRID_DIM above).
        _install_tile_grid_dim_cap()
        self.fake_image_token = AddedToken("<fake_token_around_image>", normalized=False, special=True).content
        self.image_token = AddedToken("<image>", normalized=False, special=True).content
        self.end_of_utterance_token = AddedToken("<end_of_utterance>", normalized=False, special=True).content
        self.global_image_tag = "<global-img>"  # https://github.com/huggingface/transformers/pull/32473/files/8063e5e17362571b693f1db95167f5443a3be1b2#r1734825341
        self.image_seq_len = image_seq_len
        self.image_token_id = tokenizer.convert_tokens_to_ids(self.image_token)
        self.fake_image_token_id = tokenizer.convert_tokens_to_ids(self.fake_image_token)
        self.global_image_token_id = tokenizer.convert_tokens_to_ids(self.global_image_tag)
        self.row_col_ids = self._collect_row_col_ids(tokenizer)

        # This regex matches one or more occurrences of <global-img> tags (optionally surrounded by newline characters)
        # or <row_x_col_y> tags (where x and y are digits, also optionally surrounded by newline characters).
        self._regex_to_remove_extra_special_tokens = re.compile(r"(\n?<global-img>\n?|<row_\d+_col_\d+>\n?)+")

        tokens_to_add = {
            "additional_special_tokens": [
                self.fake_image_token,
                self.image_token,
                self.end_of_utterance_token,
            ]
        }
        tokenizer.add_special_tokens(tokens_to_add)
        self.image_token_id = tokenizer.convert_tokens_to_ids(self.image_token)

        super().__init__(image_processor, tokenizer, chat_template=chat_template, **kwargs)

    @auto_docstring
    def __call__(
        self,
        images: ImageInput | list[ImageInput] | list[list[ImageInput]] = None,
        text: Union[TextInput, "PreTokenizedInput", list[TextInput], list["PreTokenizedInput"]] = None,
        audio=None,
        videos=None,
        **kwargs: Unpack[GraniteForDoclingProcessorKwargs],
    ) -> BatchEncoding:
        """
        Processes the input prompts and returns a BatchEncoding.

        This method extends the Idefics3Processor to handle GotOcr2ImageProcessor specifics.
        """
        if text is None and images is None:
            raise ValueError("You must provide either `text` or `images`.")

        output_kwargs = self._merge_kwargs(
            GraniteForDoclingProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )

        return_mm_token_type_ids = output_kwargs["text_kwargs"].pop("return_mm_token_type_ids", False)
        return_tensors = output_kwargs["text_kwargs"].pop("return_tensors", None)

        n_images_in_text = []
        n_images_in_images = []
        inputs = {}

        if text is not None:
            if isinstance(text, str):
                text = [text]
            elif not isinstance(text, list) and not isinstance(text[0], str):
                raise ValueError("Invalid input text. Please provide a string, or a list of strings")
            n_images_in_text = [sample.count(self.image_token) for sample in text]

        if images is not None:
            images = self.image_processor.fetch_images(images)
            n_images_in_images = [len(sample) if isinstance(sample, (list, tuple)) else 1 for sample in images]
            images = [[sample] if not isinstance(sample, (list, tuple)) else sample for sample in images]

            # Skip CPU-side rescale and normalize so pixel_values are transferred as uint8
            # (1 byte/pixel). The model rescales and normalizes on GPU instead.
            uint8_kwargs = dict(output_kwargs["images_kwargs"])
            uint8_kwargs["do_rescale"] = False
            uint8_kwargs["do_normalize"] = False
            image_inputs = self.image_processor(images, **uint8_kwargs)
            pv = image_inputs.get("pixel_values")
            if pv is not None:
                image_inputs["pixel_values"] = pv.to(dtype=torch.uint8)
            inputs.update(image_inputs)

            if text is not None:
                if n_images_in_images != n_images_in_text:
                    raise ValueError(
                        f"The number of images in the text {n_images_in_text} and images {n_images_in_images} should be the same."
                    )

                image_rows = []
                image_cols = []
                for sample_images in images:
                    sample_image_rows = []
                    sample_image_cols = []
                    for img in sample_images:
                        width, height = img.size
                        n_cols, n_rows = get_optimal_tiled_canvas(
                            (height, width),
                            (
                                self.image_processor.size["height"],
                                self.image_processor.size["width"],
                            ),
                            self.image_processor.min_patches,
                            self.image_processor.max_patches,
                        )
                        sample_image_rows.append(n_rows)
                        sample_image_cols.append(n_cols)
                    image_rows.append(sample_image_rows)
                    image_cols.append(sample_image_cols)

                num_patches_arr = inputs.pop("num_patches", None)
                pixel_values = inputs.get("pixel_values")
                if pixel_values is not None and len(pixel_values.shape) == 4:
                    batch_size = len(images)

                    if num_patches_arr is not None:
                        img_offset = 0
                        patches_per_sample = []
                        for sample_imgs in images:
                            n_imgs = len(sample_imgs)
                            patches_per_sample.append(int(sum(num_patches_arr[img_offset : img_offset + n_imgs])))
                            img_offset += n_imgs
                    else:
                        total = pixel_values.shape[0]
                        patches_per_sample = [total // batch_size] * batch_size

                    max_patches = max(patches_per_sample)
                    if all(p == max_patches for p in patches_per_sample):
                        inputs["pixel_values"] = pixel_values.reshape(batch_size, max_patches, *pixel_values.shape[1:])
                    else:
                        padded = torch.zeros(
                            batch_size,
                            max_patches,
                            *pixel_values.shape[1:],
                            dtype=pixel_values.dtype,
                            device=pixel_values.device,
                        )
                        pv_offset = 0
                        for i, count in enumerate(patches_per_sample):
                            padded[i, :count] = pixel_values[pv_offset : pv_offset + count]
                            pv_offset += count
                        inputs["pixel_values"] = padded

                    pam = torch.zeros(batch_size, max_patches, dtype=torch.bool)
                    for i, count in enumerate(patches_per_sample):
                        pam[i, :count] = True
                    inputs["pixel_attention_mask"] = pam

                fake_image_token = self.fake_image_token
                image_token = self.image_token
                global_img_token = self.global_image_tag

                prompt_strings = []
                compact_prompt_strings = []
                batch_image_seq_lengths = []
                for sample, sample_rows, sample_cols in zip(text, image_rows, image_cols):
                    image_prompt_strings = []
                    compact_image_prompt_strings = []
                    image_seq_lengths = []
                    for n_rows, n_cols in zip(sample_rows, sample_cols):
                        image_prompt_string = get_image_prompt_string(
                            n_rows,
                            n_cols,
                            self.image_seq_len,
                            image_token=image_token,
                            fake_token_around_image=fake_image_token,
                            global_img_token=global_img_token,
                        )
                        compact_image_prompt_string = get_compact_image_prompt_string(
                            n_rows,
                            n_cols,
                            fake_token_around_image=fake_image_token,
                            global_img_token=global_img_token,
                        )
                        row_length = (self.image_seq_len + 2) * n_cols + 1
                        image_seq_lengths.append((self.image_seq_len + 3) + row_length * n_rows)
                        image_prompt_strings.append(image_prompt_string)
                        compact_image_prompt_strings.append(compact_image_prompt_string)

                    batch_image_seq_lengths.append(image_seq_lengths)
                    split_sample = sample.split(image_token)
                    if len(split_sample) == 0:
                        raise ValueError("The image token should be present in the text.")

                    full_sample = split_sample[0]
                    compact_sample = split_sample[0]
                    for i, (full_str, compact_str) in enumerate(
                        zip(image_prompt_strings, compact_image_prompt_strings)
                    ):
                        full_sample += full_str + split_sample[i + 1]
                        compact_sample += compact_str + split_sample[i + 1]
                    prompt_strings.append(full_sample)
                    compact_prompt_strings.append(compact_sample)

                text_inputs = self.tokenizer(compact_prompt_strings, **output_kwargs["text_kwargs"])

                input_ids = text_inputs["input_ids"]
                attention_mask = text_inputs.get("attention_mask", [[1] * len(ids) for ids in input_ids])
                expanded_ids, expanded_mask = self._expand_image_tokens_in_ids(input_ids, attention_mask)
                max_len = max(len(ids) for ids in expanded_ids)
                pad_id = self.tokenizer.pad_token_id
                expanded_ids = [ids + [pad_id] * (max_len - len(ids)) for ids in expanded_ids]
                expanded_mask = [m + [0] * (max_len - len(m)) for m in expanded_mask]

                text_inputs["input_ids"] = expanded_ids
                if "attention_mask" in text_inputs:
                    text_inputs["attention_mask"] = expanded_mask

                self._check_special_mm_tokens(prompt_strings, text_inputs, modalities=["image"])
                inputs.update(text_inputs)

        elif text is not None:
            if any(n_images_in_text):
                raise ValueError(
                    f"Found {sum(n_images_in_text)} {self.image_token} tokens in the text but no images were passed."
                )
            text_inputs = self.tokenizer(text=text, **output_kwargs["text_kwargs"])
            inputs.update(text_inputs)

        if return_mm_token_type_ids:
            array_ids = np.array(inputs["input_ids"])
            mm_token_type_ids = np.zeros_like(array_ids)
            for i, seq_lengths in enumerate(batch_image_seq_lengths):
                image_start_positions = np.where(array_ids[i] == self.fake_image_token_id)[0]
                j = 0
                for seq_len in seq_lengths:
                    if j >= len(image_start_positions):
                        break
                    start = image_start_positions[j]
                    end = start + seq_len
                    mm_token_type_ids[i, start:end] = 1
                    j = np.searchsorted(image_start_positions, end)

            inputs["mm_token_type_ids"] = mm_token_type_ids.tolist()

        return BatchFeature(data=inputs, tensor_type=return_tensors)

    def prepare_inputs_layout(
        self,
        images: ImageInput | None = None,
        text: Union[TextInput, "PreTokenizedInput", list[TextInput], list["PreTokenizedInput"]] = None,
        **kwargs: Unpack[GraniteForDoclingProcessorKwargs],
    ):
        if text is not None:
            if isinstance(text, str):
                text = [text]
            text = list(text).copy()

        if images is not None:
            images = self.image_processor.fetch_images(images)
            if is_valid_image(images):
                images = [[images]]
            elif isinstance(images, (list, tuple)) and is_valid_image(images[0]):
                if text is not None:
                    # Reorganize the images to match the prompts
                    n_images_in_text = [sample.count(self.image_token) for sample in text]
                    cumsum_images_in_text = [0] + list(accumulate(n_images_in_text))
                    split_images = [
                        images[cumsum_images_in_text[i] : cumsum_images_in_text[i + 1]]
                        for i in range(len(n_images_in_text))
                    ]
                    # Append the rest if any, we will error out when validating if they don't match with text
                    if len(images) > cumsum_images_in_text[-1]:
                        images = split_images + [images[cumsum_images_in_text[-1] :]]
                    else:
                        images = split_images
                else:
                    images = [images]

        return images, text

    def validate_inputs(
        self,
        images: ImageInput | None = None,
        text: Union[TextInput, "PreTokenizedInput", list[TextInput], list["PreTokenizedInput"]] = None,
        **kwargs: Unpack[GraniteForDoclingProcessorKwargs],
    ):
        super().validate_inputs(images, text, **kwargs)

        if text is None and images is None:
            raise ValueError("You must provide either `text` or `images`.")

        if text is not None:
            n_images_in_text = [sample.count(self.image_token) for sample in text]
            if images is not None:
                n_images_in_images = [len(sublist) for sublist in images]
                if n_images_in_text != n_images_in_images:
                    raise ValueError(
                        f"The total number of {self.image_token} tokens in the prompts should be the same as the number of images passed."
                        f" Found {n_images_in_text} {self.image_token} tokens and {n_images_in_images} images per sample."
                    )
            elif images is None and any(n_images_in_text):
                raise ValueError(
                    f"Found {sum(n_images_in_text)} {self.image_token} tokens in the text but no images were passed."
                )

    def replace_image_token(self, image_inputs: dict, image_idx: int, **kwargs) -> str:
        image_rows = [row for row_list in image_inputs["rows"] for row in row_list][image_idx]
        image_cols = [col for col_list in image_inputs["cols"] for col in col_list][image_idx]
        if image_rows == 0 and image_cols == 0:
            return (
                f"{self.fake_image_token}"
                + f"{self.global_image_tag}"
                + f"{self.image_token}" * self.image_seq_len
                + f"{self.fake_image_token}"
            )
        else:
            text_split_images = ""
            for n_h in range(image_rows):
                for n_w in range(image_cols):
                    text_split_images += (
                        f"{self.fake_image_token}"
                        + f"<row_{n_h + 1}_col_{n_w + 1}>"
                        + f"{self.image_token}" * self.image_seq_len
                    )
                text_split_images += "\n"

            text_split_images += (
                f"\n{self.fake_image_token}"
                + f"{self.global_image_tag}"
                + f"{self.image_token}" * self.image_seq_len
                + f"{self.fake_image_token}"
            )
            return text_split_images

    def create_mm_token_type_ids(self, input_ids: list, batch_image_seq_lengths: list[int]) -> list[list[int]]:
        # We have to iterate for each list separately because inputs
        # might be non-padded lists and we can't cast numpy on that!
        # Then cast numpy as each input for faster indexing
        mm_token_type_ids = []
        for i, seq_lengths in enumerate(batch_image_seq_lengths):
            array_ids = np.array(input_ids[i])
            mm_token_types = np.zeros_like(array_ids)
            image_start_positions = np.where(array_ids == self.fake_image_token_id)[0]
            j = 0
            for seq_len in seq_lengths:
                if j >= len(image_start_positions):
                    break
                start = image_start_positions[j]
                end = start + seq_len
                mm_token_types[start:end] = 1
                j = np.searchsorted(image_start_positions, end)
            mm_token_type_ids.append(mm_token_types.tolist())

        return mm_token_type_ids

    def _get_num_multimodal_tokens(self, image_sizes=None, **kwargs):
        """
        Computes the number of placeholder tokens needed for multimodal inputs with the given sizes.

        Args:
            image_sizes (`list[list[int]]`, *optional*):
                The input sizes formatted as (height, width) per each image.

        Returns:
            `MultiModalData`: A `MultiModalData` object holding number of tokens per each of the provided
            input modalities, along with other useful data.
        """

        vision_data = {}
        if image_sizes is not None:
            images_kwargs = GraniteForDoclingProcessorKwargs._defaults.get("images_kwargs", {})
            images_kwargs.update(kwargs)

            num_image_row_cols = [
                self.image_processor.get_number_of_image_patches(*image_size, images_kwargs)
                for image_size in image_sizes
            ]

            base_image_length = self.image_seq_len + 3
            col_length = self.image_seq_len + 2
            # For split images the global section is preceded by "\n" which together with the
            # row-trailing "\n" forms "\n\n". Some tokenizers merge "\n\n" into one token; others
            # (e.g. trimmed/tiny tokenizers) keep them as two. Count accurately so the formula
            # matches the actual tokenized output regardless of the tokenizer's merge rules.
            extra_split_newline = len(self.tokenizer("\n\n", add_special_tokens=False)["input_ids"]) - 1
            num_image_tokens = []
            num_image_patches = []

            for num_patches, num_rows, num_cols in num_image_row_cols:
                row_length = col_length * num_cols + 1
                split_extra = extra_split_newline if num_rows > 0 else 0
                num_image_tokens.append(base_image_length + split_extra + (row_length * num_rows))
                num_image_patches.append(num_patches)

            vision_data.update({"num_image_tokens": num_image_tokens, "num_image_patches": num_image_patches})

        return MultiModalData(**vision_data)

    @staticmethod
    def _collect_row_col_ids(tokenizer) -> set[int]:
        if tokenizer is None:
            return set()
        unk_id = tokenizer.unk_token_id
        return {
            tid
            for tid in (
                tokenizer.convert_tokens_to_ids(f"<row_{i + 1}_col_{j + 1}>") for i in range(16) for j in range(16)
            )
            if tid != unk_id
        }

    def _expand_image_tokens_in_ids(
        self,
        input_ids: list[list[int]],
        attention_mask: list[list[int]],
    ) -> tuple[list[list[int]], list[list[int]]]:
        """Insert image_seq_len <image> token IDs after each row/col and global-img marker."""
        image_token_id = self.image_token_id
        row_col_ids = self.row_col_ids
        global_id = self.global_image_token_id
        image_seq_len = self.image_seq_len
        image_fill = [image_token_id] * image_seq_len
        mask_fill = [1] * image_seq_len

        expanded_ids = []
        expanded_mask = []
        for ids_row, mask_row in zip(input_ids, attention_mask):
            new_ids: list[int] = []
            new_mask: list[int] = []
            for tok_id, m in zip(ids_row, mask_row):
                new_ids.append(tok_id)
                new_mask.append(m)
                if tok_id in row_col_ids or tok_id == global_id:
                    new_ids.extend(image_fill)
                    new_mask.extend(mask_fill)
            expanded_ids.append(new_ids)
            expanded_mask.append(new_mask)
        return expanded_ids, expanded_mask


__all__ = ["GraniteForDoclingProcessor"]
